### ISSUE TITLE
Refactor api_mid

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_mid#1]
Realizar refactor del api mid para el sistema de cumplidos teniendo en cuenta los lineamientos suministrados por la OAS

https://github.com/udistrital/lineamientos_oas#generaci%C3%B3n-api-mid

**Comment by diagutierrezro** [comment]
Se realiza el refactor del api mid realizando un cambio con respecto a los lineamientos en el manejo de errores que se realiza en los controladores (Ahora se realiza manejándolo con panic y defer) y a la información mostrada cuando se genere un error especifico. Los controladores que han sido refactorizados hasta la fecha son:
- certificacion
- contratos_contratista
- solicitudes_coordinador
- solicitudes_ordenador_contratistas

**Comment by anndresfelipe29** [comment]
Se termina de realizar el refactor de todo el MID y se propone una nueva manera de realizarlo, la cual ahora se encuentra documentada en los lineamientos de la OAS en:  https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/logica_orientada_a_funciones.md

En este refactor se enfoca el control de errores por medio de panic, defer y recover.

**Comment by diagutierrezro** [comment]
El nuevo refactor que se hizo con @anndresfelipe29 se realiza de la siguiente manera:

- Los controllers ahora realizan el manejo de errores con panic y defer de la siguiente manera:
![image](https://user-images.githubusercontent.com/38676533/103564050-d96aae00-4e8b-11eb-9248-f79a631cba3c.png)
Agregando que desde los controllers se manejan los errores si se introducen parámetros incorrectos

- Dado que ahora la lógica se maneja desde los helpers en ellos se manejan 2 tipos de errores, cuando responde un código incorrecto (normalmente para peticiones get debe responde 200 o para post 201) y cuando la petición que se realiza falla, esto se maneja desde los if y si estos fallan se maneja el error desde los else, como en el siguiente ejemplo:
![image](https://user-images.githubusercontent.com/38676533/103564658-e9cf5880-4e8c-11eb-879e-3065805f8940.png)
Esto se realiza para cada petición a un servicio.

- Cuando se realiza una petición y esta falla Go arroja unos panics de error por lo que desde los helpers se maneja un defer para  controlar estos errores
- 
![image](https://user-images.githubusercontent.com/38676533/103564963-71b56280-4e8d-11eb-959f-d38a9c13434d.png)
