### ISSUE TITLE
Actualización de módulo version ll vs producción.

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/cumplidos_mid#17]
Actualizar la versión que estamos desarrollando vs los últimos requerimientos o ajustes solicitados por el usuario.

**Comment by Eduargonzalez** [comment]
Se realizo una reunión con @OscarDuarte7  encargado del soporte de dicho módulo donde nos explico cada uno de los ajustes realizados al sistema. Se miraron estos RFC y se hizo la respectiva actualización al módulo.

- [ ] Cambio   en la consulta del servicio JBPM contratos_dependencia - https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=34571

- [ ] Cambiar   Estado de Cumplidos Emisora Mes de Mayo 2020
 https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=36307

- [ ] Modificar Servicio Contratos_Contratista Administrativa_Mid_Api    https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=36759

- [ ] Ajustar el servicio de JBPM contratos_persona                                             https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=37189

- [ ] Modificar   Servicio de administrativa_mid_api contratos_contratista | https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=39380

- [ ] Modificar Controlador Aprobacion_Pago en el servicio Contratos_Contratista de   Administrativa_Mid_Api | https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=39869

- [ ] Ajustar lógica Cumplidos CPS 
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=40019

- [ ] Ajustar Controlador aprobacion_pago Administrativa Mid Api 
 https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=40310

**Comment by diagutierrezro** [comment]
Después de la explicación recibida por  @OscarDuarte7  se dice que unos de estos ajustes se realizaron en JBPM   por lo que no se deben realizar en el nuevo cumplidos, estos cambios realizados para su ajuste se pueden evidenciar en el siguiente commit: https://github.com/udistrital/cumplidos_mid/commit/ca5fd0cba12684858e339468578bcdbd31110144 

El ultimo cambio mencionado que ajusta los controladores de aprobación pago se encuentra en https://github.com/udistrital/cumplidos_mid/commit/c2a2dcd72733250533207088f24d703196dfc74f . El cliente ya se probó con los nuevos cambios realizados al mid y no se evidenciaron errores
