### ISSUE TITLE
Creación de EndPoints para traer la información necesaria en el informe

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_mid#31]
Se debe realizar la creación de EndPoints y las tareas que esto requiera (Creación o ajuste de controladores, helpers, modelos, rutas), de forma que permitan obtener la información necesaria para automatizar la mayor parte del informe de gestión y de certificado de cumplimiento,

**Nota**: Tener en cuenta la [Información necesaria para el proceso de automatización](https://github.com/udistrital/cumplidos_cliente/issues/113)

**Comment by JuanCamiloMartinezLopez** [comment]
Se comienza el desarrollo del endpoint en el mid para la obtención del  la [informacion](https://github.com/udistrital/cumplidos_cliente/issues/113) del informe. Se desconoce como se debe traer la siguiente informacion:
- **Metas**/necesidades_crud.
- **RP**/JBPM o kronos
- **CPS**/JBPM o kronos
- **Valor a pagar**/titan_crud
- **Periodo a pagar**/titan_crud
- **nombre entidad bancaria**/ desconocido

se solicita una guiá sobre estos sistemas y como poder obtener la informacion necesaria.

**Comment by a52290451** [comment]
Se solicita información de los sistemas mencionados. Se espera realizar una reunión pronto respecto a lo solicitado.
