### ISSUE TITLE
Pruebas Unitarias - Automatización de informe de gestión y certificado de cumplimiento

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_mid#37]
Implementar pruebas unitarias en API CRUD y MID, asociadas al módulo de automatización de informe de gestión y certificado de cumplimiento.

**Criterios de aceptación**

- [x] Commit con las pruebas implementadas

**Comment by JuanCamiloMartinezLopez** [comment]
### Pruebas unitarias MID
se realizan las pruebas unitarias de los contraladores y helpers de los nuevos endpoint:
- Informacion_informe

![imagen](https://user-images.githubusercontent.com/42418412/196570767-3cbd5d0c-0764-4e48-ae13-992ae7722c90.png)


- Informe

![imagen](https://user-images.githubusercontent.com/42418412/196570623-36ea6508-be8f-43cd-9f05-bb2eb0d1de64.png)


- Validacion_fecha_carga_cumplido

![imagen](https://user-images.githubusercontent.com/42418412/196570693-c79e23b2-affa-4fa5-b64b-ed21de14330a.png)
