### ISSUE TITLE
Pruebas unitarias del api mid

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_mid#5]
Revisar el funcionamiento de pruebas unitarias para el api mid de cumplidos dados los lineamientos sministrados por la OAS 

https://github.com/udistrital/lineamientos_oas/blob/master/pruebas_unitarias_api_beego/paso_parametro_test_mid.md

**Comment by diagutierrezro** [comment]
Junto con @anndresfelipe29 se realizan las pruebas unitarias del mid de cumplidos las cuales son realizadas a los helpers del sistema donde en cada uno de estos helpers de prueba que se crean se definen las variables de entorno necesarias
![image](https://user-images.githubusercontent.com/38676533/103791094-08119180-5010-11eb-8986-3dfe1f887bb6.png)

Despues en cada función de estos helpers se hace un llamado al helper correspondiente y se le pasan algunos parametros necesarios para que funcione de manera correcta.
![image](https://user-images.githubusercontent.com/38676533/103791222-2f685e80-5010-11eb-97a8-79f375be8593.png)

Finalmente para realizar las pruebas se fijan las variables de entorno en la petición seguido del comando go test ./... -v y allí se realizan las pruebas
![image](https://user-images.githubusercontent.com/38676533/103795226-b8cd6000-5013-11eb-97d8-5011b44a9308.png)
