### ISSUE TITLE
Pruebas de smoke api mid

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_mid#6]
Revisar el funcionamiento de las pruebas de smoke suministradas por la OAS

https://github.com/udistrital/lineamientos_oas/blob/master/pruebas_unitarias_api_beego/smoke_test_mid.md

**Comment by anndresfelipe29** [comment]
En compañia @diagutierrezro se realizan las pruebas de smoke correspondientes a los 6 controladores del api_mid . 
Las pruebas se encuentran en la ruta test/controllers  y se organizan de la siguiente manera:
![image](https://user-images.githubusercontent.com/30865375/103814797-5171d900-5030-11eb-828b-bffbedb54193.png)

Para cada endpoint se estructuran dos pruebas, la primera  verifica una respuesta correcta y otra donde se verifica la respuesta ante un error de petición como se ve a continuación:

![image](https://user-images.githubusercontent.com/30865375/103816160-8848ee80-5032-11eb-81da-c2759c90c519.png)
