### ISSUE TITLE
Diagnóstico de controladores por optimizar

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_mid#78]
Revisar los controladores que se deben optimizar. apoyándose en [controladores](https://github.com/udistrital/cumplidos_cliente/issues/275). Se sugieren inicialmente: certificación, contratos_contratistas e información_informe.

**Criterios de aceptación**

- [ ] Comentario en el issue relacionando los controladores a optimizar.

**Comment by JuanCamiloMartinezLopez** [comment]
# Diagnóstico de controladores (Helpers)
Se realiza una revisión de los controladores usados en cumplidos para su optimización y se realizan las siguientes propuestas:
- ***Creación de un helper para el manejo y consulta de novedades:***
Debido a la fuerte dependencia de cumplidos a las novedades contractuales, la consulta de estas se realiza en varios procesos por eso se propone la creación de funciones que ayuden a consultar y manejar estas novedades, reduciendo código duplicado.
- ***Creación de una transacción para guardar y actualizar un informe:***
Se observa que al ser una estructura compleja la cual almacena información en diferentes tablas, es vulnerable al momento de insertar o actualizar la información una a una, por lo que se propone crear una transacción que permita realizar un rollback si falla alguna operación, para  evitar a si data duplicada  y reducir código en el mid.
- ***Optimización de tiempos de solicitudes de ordenador y supervisor:***
Estas peticiones que traen grandes cantidades de registros se podrían optimizar intentando utilizar goroutines para mejorar sus tiempos.
- ***Eliminaciones de helpers y controladores de cumplidos docentes:***
El sistema contiene código pensado para cumplidos docentes, este sin ser usado por lo que si cumplidos docente es independizado podría eliminarse este código.
## Sugerencias:
Aparte de las recomendaciones anteriores se propone también lo siguiente:
- ***Eliminar archivos basura en cumplidos_cliente:***
Cumplidos cliente al ser un sistema que se basó de un sistema predecesor contiene muchas dependencias y archivos que no son utilizados, haciendo que este código sea más complicado de entender de lo que realmente es.
- ***Extracción de lógica de cumplidos cliente:***
Actualmente en cumplidos cliente se realizan muchos procesos de la lógica que se podrían extraer y realizar en el cliente, o bien simplificar para evitar tener archivos javascript tan pesados y complejos
