### ISSUE TITLE
Optimizar guardado de informe y sus respectivas actividades

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_mid#80]
Creación de una transacción para guardar y actualizar un informe.

**Criterios de aceptación** 

- [x]  Verificación de proceso de creación de una única transacción con consumo de varios endpoints.
- [x] Creación de la transacción.
- [x]  Prueba de funcionamiento correcto del cambio
- [x]  Commit del cambio
- [x]  PR a develop

**Comment by JuanCamiloMartinezLopez** [comment]
## transacción 
Se plantea el uso de dos transacciones que funcionan bajo los mismos endpoints de insert y update, esto validando si el informe contiene actividades, de ser así se realizara el tratamiento de un informe completo.
![imagen](https://user-images.githubusercontent.com/42418412/209587141-ff7e25c1-cb96-4f0a-8b63-4d6e36bdf568.png)
Para las transacciones se definen dos funciones:
- **AddInformeCompleto:**
![imagen](https://user-images.githubusercontent.com/42418412/209587329-a445c2e6-09f5-4079-9e60-fc5f37af546d.png)
- **UpdateInformeCompleto:**
![imagen](https://user-images.githubusercontent.com/42418412/209587288-cf9ea03c-c8a6-4222-b22f-13bb08d10207.png)

Esto permite seguir manejando el uso anterior del update y insert del informe, actividad_realizada y actividad_realizada y tener el proceso de insertar y/o guardar un informe completo directamente desde el crud, logrando evitar guardados parciales de informacion.
