### ISSUE TITLE
Optimización de tiempos de solicitudes de ordenador y supervisor

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_mid#81]
Revisar la implementación de gorutines para manejar hilos que permitan realizar varias consultas en paralelo  asociadas a los ordenadores y supervisores.

**Criterios de aceptación**

- [x]  Implementación de go routines.
- [x]  Prueba de funcionamiento correcto del cambio
- [x]  Commit del cambio

**Comment by JuanCamiloMartinezLopez** [comment]
### Optimización de tiempos con goroutines

Se utilizan goroutines para realizar las consultas concurrentes para reducir tiempos en las peticiones de solicitudes de supervisor y ordenador:
- sin goroutines
![antes_goroutines](https://user-images.githubusercontent.com/42418412/221873049-3f8db01b-4431-456b-9f0e-a7c67abc6357.png)
- con goroutines
![despues_goroutines](https://user-images.githubusercontent.com/42418412/221873099-7e5e5777-c65b-4d73-88b6-dacaebdd65ed.png)
